DROP TABLE IF EXISTS actors;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS roles;


CREATE TABLE actors (
  id SERIAL4 PRIMARY KEY,
  first_name VARCHAR(255),
  last_name VARCHAR(255)
);

CREATE TABLE movies (
  id SERIAL4 PRIMARY KEY,
  title VARCHAR(255),
  genre VARCHAR(255)
);

CREATE TABLE roles (
id SERIAL4 PRIMARY KEY,
actor_id INT4 REFERENCES actors(id) ON DELETE CASCADE,
movie_id INT4 REFERENCES movies(id) ON DELETE CASCADE,
fee INT8
  );
